### ISSUE TITLE
Operation Code bug for large LITERALs

### ISSUE THREAD

**Issue by DevinHightail** [sergey-raevskiy/librsync-csharp#1]
In DeltaEmitter::Literal() line #52:
                var op = lCount + 64;
This works correctly for one-byte or two-byte integer parameters, but as soon as you need more than two bytes for a parameter then it is wrong.  
- one-byte integer is opcode 65 (64+1)
- two-byte integer is opcode 66 (64+2)
- four-byte integer should be opcode 67 (64+3) but it is producing opcode 68 (64+4)
- eight-byte integer should be opcode 68 (64+4) but it is producing opcode 72 (64+8), which is a COPY opcode.

It should be should be: 
    pseudocode:   op = 64 + (log2(lCount)+1)
    C# code:          int op = 65 + (int)System.Math.Log(lCount, 2); // 64 + (log2(n) + 1)

There is a similar problem in generating the COPY opcodes on line #36, but that one is more complicated with bit-shifting (as the comment "MAGIC" alludes to).

**Comment by sergey-raevskiy** [comment]
Thanks for a feedback! Can you please make some tests for this cases?

**Comment by sergey-raevskiy** [comment]
Thanks, fixed in 56dfa76f89440694339a23e1b71dbee9eefc5a60. Nevermind the commit message, I've messed the issue number.
