### ISSUE TITLE
GetIntLen() is wrong for integers larger than 3 bytes

### ISSUE THREAD

**Issue by DevinHightail** [sergey-raevskiy/librsync-csharp#2]
In DeltaEmitter::Literal() line #20:
            else if (i <= 0xffffff)
should be:
            else if (i <= 0xffffffff)
so GetIntLen() will return 4 until the integer is larger than four bytes (instead of larger than just three bytes).

**Comment by sergey-raevskiy** [comment]
Thanks for reporting! Fixed in 7246b126fb55ad6d93b5382cca15628378f0af04 (using the original librsync code).
